[env]
GOPATH = "{{env.PWD}}/.go"

[tools]
go = "latest"
golangci-lint = "latest"
goreleaser = "latest"

[tasks.build]
description = "Build the tofusort binary"
run = "go build -o tofusort ./cmd/tofusort"

[tasks.check]
description = "Run all checks (format, lint, test)"
depends = ["fmt", "lint", "test"]

[tasks.clean]
description = "Clean build artifacts"
run = "rm -f tofusort"

[tasks.dev]
description = "Development validation cycle"
depends = ["check"]

[tasks.fmt]
description = "Format Go code"
run = "go fmt ./..."

[tasks.install]
description = "Install tofusort binary to GOPATH/bin"
run = "go install ./cmd/tofusort"

[tasks.lint]
description = "Run linter"
run = "golangci-lint run"

[tasks.test]
description = "Run all tests"
run = "go test -v ./..."
